taskgenuis_db



-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.schedule
(
    id serial NOT NULL,
    user_id bigint,
    task_id bigint,
    scheduled_time timestamp without time zone NOT NULL,
    schedule_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "timestamp" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT schedule_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tasks
(
    task_id bigint NOT NULL DEFAULT nextval('tasks_id_seq'::regclass),
    user_id bigint,
    task_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    task_description character varying(255) COLLATE pg_catalog."default",
    priority character varying(255) COLLATE pg_catalog."default" NOT NULL,
    estimated_duration character varying(255) COLLATE pg_catalog."default" NOT NULL,
    status character varying(255) COLLATE pg_catalog."default" DEFAULT 'Pending'::character varying,
    created_at character varying(255) COLLATE pg_catalog."default" DEFAULT CURRENT_TIMESTAMP,
    deadline character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT tasks_pkey PRIMARY KEY (task_id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    user_id bigint NOT NULL DEFAULT nextval('users_id_seq'::regclass),
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    username character varying(255) COLLATE pg_catalog."default",
    firstname character varying(255) COLLATE pg_catalog."default",
    lastname character varying(255) COLLATE pg_catalog."default",
    role character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT users_pkey PRIMARY KEY (user_id),
    CONSTRAINT users_email_key UNIQUE (email)
);

ALTER TABLE public.users
ADD COLUMN display_name character varying(255) COLLATE pg_catalog."default",
ADD COLUMN profile_pic character varying(255) COLLATE pg_catalog."default";

ALTER TABLE IF EXISTS public.schedule
    ADD CONSTRAINT schedule_task_id_fkey FOREIGN KEY (task_id)
    REFERENCES public.tasks (task_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.schedule
    ADD CONSTRAINT schedule_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.tasks
    ADD CONSTRAINT tasks_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;


